# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eUCs1hFBeZfdT1iTmntD990COwDwG5L7
"""
import streamlit as st
import numpy as np
from PIL import Image, ImageDraw
import tempfile, os
from gtts import gTTS
from moviepy.editor import ImageSequenceClip, AudioFileClip, CompositeAudioClip

st.set_page_config(page_title="AI Video Generator", page_icon="🎬")
st.title("🎬 AI Scene Video Generator")

if 'video' not in st.session_state:
    st.session_state.video = None

def create_scene_image(text):
    img = Image.new('RGB', (800, 600))
    draw = ImageDraw.Draw(img)
    h = hash(text) % 360
    for y in range(600):
        draw.rectangle([(0,y),(800,y+1)], fill=(100+int(y/6), 80+int(y/5), 150+int(y/7.5)))
    words = text.lower()
    if 'mountain' in words or 'peak' in words:
        draw.polygon([(100,500),(300,200),(500,500)], fill=(60,60,80))
    if 'sun' in words:
        draw.ellipse([600,100,700,200], fill=(255,200,100))
    if 'ocean' in words or 'sea' in words:
        for i in range(5):
            draw.ellipse([0,400+i*30,200,440+i*30], fill=(100,150,200))
    draw.rectangle([50,500,750,550], fill=(0,0,0))
    draw.text((60,510), text[:60], fill=(255,255,255))
    return img

def make_video(scenes):
    frames, audios, temps = [], [], []
    try:
        for i, scene in enumerate(scenes):
            st.write(f"Scene {i+1}/3...")
            img = create_scene_image(scene)
            for f in range(150):
                z = 1 + f/1000
                w, h = int(800*z), int(600*z)
                zoomed = img.resize((w,h), Image.Resampling.LANCZOS)
                frames.append(np.array(zoomed.crop(((w-800)//2,(h-600)//2,(w+800)//2,(h+600)//2))))
            aud = tempfile.NamedTemporaryFile(delete=False, suffix='.mp3')
            aud.close()
            temps.append(aud.name)
            tts = gTTS(scene, lang='en')
            tts.save(aud.name)
            audios.append(aud.name)
        
        clip = ImageSequenceClip(frames, fps=30)
        audio_clips = [AudioFileClip(a).subclip(0,min(AudioFileClip(a).duration,5)).set_start(i*5) for i,a in enumerate(audios)]
        clip = clip.set_audio(CompositeAudioClip(audio_clips)).set_duration(15)
        
        out = tempfile.NamedTemporaryFile(delete=False, suffix='.mp4')
        out.close()
        clip.write_videofile(out.name, fps=30, codec='libx264', audio_codec='aac', logger=None, preset='ultrafast')
        clip.close()
        return out.name
    except Exception as e:
        st.error(f"Error: {e}")
        return None

scenes = [st.text_area(f"Scene {i+1}", placeholder="Describe scene...", key=f"s{i}", height=60) for i in range(3)]

if st.button("Generate Video", type="primary"):
    if all(s.strip() for s in scenes):
        st.session_state.video = make_video(scenes)
        st.balloons()
    else:
        st.error("Fill all scenes!")

if st.session_state.video and os.path.exists(st.session_state.video):
    with open(st.session_state.video, 'rb') as f:
        vb = f.read()
    st.video(vb)
    st.download_button("Download", vb, "video.mp4", "video/mp4")
