# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eUCs1hFBeZfdT1iTmntD990COwDwG5L7
"""

import streamlit as st, numpy as np, tempfile, os
from PIL import Image, ImageDraw, ImageFont
from gtts import gTTS
from moviepy.editor import ImageSequenceClip, AudioFileClip, CompositeAudioClip

st.set_page_config("AI Scene Video", "🎬")
st.title("🎬 Scene → 15s Video")

def gen_img(text, w=800, h=600):
    img, draw = Image.new("RGB", (w, h)), ImageDraw.Draw(img)
    hash_val = hash(text) % 360
    for y in range(h):
        r, g, b = int(100+y/h*100+hash_val%55), int(80+y/h*120+(hash_val*2)%55), int(150+y/h*80+(hash_val*3)%55)
        draw.line([(0,y),(w,y)], fill=(r,g,b))

    t = text.lower()
    if "sun" in t: draw.ellipse([600,100,720,220],200)
    if "mountain" in t: draw.polygon([(100,500),(300,200),(500,500)],60)
    if "forest" in t:
        for i in range(6): x=50+i*130; draw.rectangle([x+20,350,x+40,500],101); draw.ellipse([x-20,280,x+80,380],34)

    font = ImageFont.load_default()
    txt = text[:50]+"..." if len(text)>50 else text
    tw, th = draw.textbbox((0,0),txt,font=font)[2:]
    x, y = (w-tw)//2, h-100
    draw.rectangle([x-10,y-5,x+tw+10,y+th+5]); draw.text((x,y-2), txt, 255, font=font)
    return img

def frames(img, n=150):
    f,w,h = [],img.width,img.height
    for i in range(n):
        z = img.resize((int(w*(1+i/n*0.15)), int(h*(1+i/n*0.15))))
        f.append(np.array(z.crop(((z.width-w)//2,(z.height-h)//2,(z.width+w)//2,(z.height+h)//2))))
    return f

def audio(text, fn): gTTS(text).save(fn)

def video(scenes):
    F,A = [],[]
    for s in scenes:
        img = gen_img(s); F+=frames(img)
        af = tempfile.mktemp(".mp3"); audio(s,af); A.append(AudioFileClip(af).set_start(len(A)*5))
    clip = ImageSequenceClip(F,30).set_duration(15)
    clip.set_audio(CompositeAudioClip(A)).write_videofile(vf:=tempfile.mktemp(".mp4"),30,"libx264","aac",False,preset="ultrafast")
    return vf

S=[st.text_area(f"Scene {i+1}",key=i) for i in range(3)]
if st.button("Generate Video") and all(s.strip() for s in S):
    v=video(S); st.video(open(v,"rb").read())
    st.download_button("Download",open(v,"rb").read(),"video.mp4","video/mp4")
elif st.button("Generate Video"): st.error("Fill all scenes!")